"""create users, accounts, and payments tables

Revision ID: c488a6c5bae5
Revises:
Create Date: 2026-08-08 13:33:37.168004

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c488a6c5bae5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column(
        'created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column(
        'created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(
        ['user_id'], ['users.id'], name=op.f('fk_accounts_user_id_users'), ondelete='CASCADE'
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column(
        'created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(
        ['account_id'],
        ['accounts.id'],
        name=op.f('fk_payments_account_id_accounts'),
        ondelete='CASCADE',
    ),
    sa.ForeignKeyConstraint(
        ['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users'), ondelete='CASCADE'
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_account_id'), 'payments', ['account_id'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)

    users = sa.table(
        'users',
        sa.column('id', sa.Integer),
        sa.column('email', sa.String),
        sa.column('full_name', sa.String),
        sa.column('hashed_password', sa.String),
        sa.column('is_admin', sa.Boolean),
    )
    accounts = sa.table(
        'accounts',
        sa.column('id', sa.Integer),
        sa.column('user_id', sa.Integer),
        sa.column('balance', sa.Numeric(18, 2)),
    )

    op.bulk_insert(
        users,
        [
            {
                'id': 1,
                'email': 'user@example.com',
                'full_name': 'Test User',
                'hashed_password': '$2b$12$.IGoncMssraYiNRcuJ64b./6QxCE6S4uCbgR6EQlVoNf5yQvPivcu',
                'is_admin': False,
            },
            {
                'id': 2,
                'email': 'admin@example.com',
                'full_name': 'Test Admin',
                'hashed_password': '$2b$12$oMJpmz0Oz7fckZwWjbTrke8Mo0mgw3./Y5xCfycRBt0TIZAlX8vMK',
                'is_admin': True,
            },
        ],
    )
    op.bulk_insert(
        accounts,
        [{'id': 1, 'user_id': 1, 'balance': 0}],
    )
    op.execute("SELECT setval(pg_get_serial_sequence('users', 'id'), (SELECT max(id) FROM users))")
    op.execute(
        "SELECT setval(pg_get_serial_sequence('accounts', 'id'), (SELECT max(id) FROM accounts))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_account_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
